<UserProfileScreen>:
    name: "user_screen"
    orientation: 'vertical'
    MDTopAppBar:
        id: topbar
        title: "Perfil!"
        pos_hint: {"top": 1}
        size_hint_y: .10             
        title_center: True
        right_action_items: [["robot-happy"]]
        size_hint_y: 0.81  # Ajusta el tamaño de la tarjeta
        orientation: 'vertical'
        padding: dp(20)

